// utils/marvelNames.js
export const marvelCharacters = [
  "Iron Man",
  "Captain America",
  "Thor",
  "Hulk",
  "Black Widow",
  "Hawkeye",
  "Spider-Man",
  "Doctor Strange",
  "Black Panther",
  "Captain Marvel",
  "Scarlet Witch",
  "Vision",
  "Falcon",
  "Winter Soldier",
  "Star-Lord",
  "Gamora",
  "Drax",
  "Rocket",
  "Groot",
  "Nebula",
  "Mantis",
  "Yondu",
  "Loki",
  "Thanos",
  "Deadpool",
  "Wolverine",
  "Storm",
  "Cyclops",
  "Jean Grey",
  "Professor X",
  "Magneto",
  "Mystique",
  "Nick Fury",
  "Ant-Man",
  "Wasp",
  "Shuri",
  "Okoye",
  "Valkyrie",
  "Korg",
  "Miek",
  "Heimdall",
  "Odin",
  "Hela",
  "Surtur",
  "Ego",
  "Dormammu",
  "Ultron",
  "Red Skull",
  "Zemo",
  "Crossbones",
  "Killmonger",
  "Klaw",
  "M'Baku",
  "Nakia",
  "Aunt May",
  "Happy Hogan",
  "Pepper Potts",
  "War Machine",
  "Rescue",
  "Maria Hill",
  "Phil Coulson",
  "Talos",
  "Soren",
  "Monica Rambeau",
  "Darcy Lewis",
  "Jimmy Woo",
  "Agatha Harkness",
  "White Vision",
  "America Chavez",
  "Kate Bishop",
  "Yelena Belova",
  "Shang-Chi",
  "Katy",
  "Xialing",
  "Wong",
  "Abomination",
  "Moon Knight",
  "Marc Spector",
  "Steven Grant",
  "Jake Lockley",
  "Khonshu",
  "Harrow",
  "Ms. Marvel",
  "Kamala Khan",
  "Bruno Carrelli",
  "Nakia Bahadir",
  "She-Hulk",
  "Jennifer Walters",
  "Nikki Ramos",
  "Pug",
  "Blade",
  "Morbius",
  "Ghost Rider",
  "Punisher",
  "Daredevil",
  "Kingpin",
  "Elektra",
  "Bullseye",
  "Luke Cage",
  "Iron Fist",
  "Jessica Jones",
  "Colleen Wing",
  "Misty Knight",
  "Echo",
  "Namor",
  "Attuma",
  "Namorita",
  "Hank Pym",
  "Janet van Dyne",
  "Scott Lang",
  "Hope van Dyne",
  "Cassie Lang",
  "Kang the Conqueror",
  "Ravonna Renslayer",
  "Victor Timely",
  "Mobius",
  "Hunter B-15",
  "Sylvie",
  "Laufey",
  "Frigga",
  "Jane Foster",
  "Mighty Thor",
  "Love",
  "Gorr",
  "Zeus",
  "Hercules",
  "Bast",
  "Ares",
  "Eternity",
  "Infinity",
  "Watcher",
  "Arishem",
  "Kro",
  "Ikaris",
  "Sersi",
  "Thena",
  "Druig",
  "Makkari",
  "Phastos",
  "Kingo",
  "Sprite",
  "Ajak",
  "Gilgamesh",
  "Dane Whitman",
  "Black Knight",
  "Pip the Troll",
  "Eros",
  "Starfox",
  "Harry Styles",
  "Adam Warlock",
  "Ayesha",
  "High Evolutionary",
  "Lylla",
  "Teefs",
  "Floor",
  "Nova",
  "Quasar",
  "Beta Ray Bill",
  "Silver Surfer",
  "Galactus",
  "Firelord",
  "Terrax",
  "Morg",
  "Air-Walker",
  "Destroyer",
  "Surtur",
  "Ymir",
  "Ulik",
  "Kurse",
  "Malekith",
  "Enchantress",
  "Executioner",
  "Amora",
  "Skurge",
  "Fandral",
  "Hogun",
  "Volstagg",
  "Sif",
  "Balder",
  "Tyr",
  "Heimdall",
  "Idunn",
  "Brunnhilde",
  "Hela",
  "Fenris",
  "Jormungand",
  "Skadi",
  "Cul",
  "Serpent",
  "Nerkkod",
  "Greer",
  "Sin",
  "Crossbones",
  "Madame Hydra",
  "Viper",
  "Red Hulk",
  "A-Bomb",
  "Leader",
  "Abomination",
  "Skaar",
  "Hiroim",
  "Caiera",
  "Miek",
  "No-Name",
  "Elloe",
  "Korg",
  "Lavender",
  "Death's Head",
  "M.O.D.O.K.",
  "Super-Adaptoid",
  "Arnim Zola",
  "Baron Zemo",
  "Helmut Zemo",
  "Heinrich Zemo",
  "Swordsman",
  "Moonstone",
  "Songbird",
  "Atlas",
  "MACH-X",
  "Fixer",
  "Beetle",
  "Speed Demon",
  "Joystick",
  "Radioactive Man",
  "Whirlwind",
  "Tiger Shark",
  "Armadillo",
  "Puma",
  "Man-Ape",
  "Mandarin",
  "Fin Fang Foom",
  "Living Laser",
  "Crimson Dynamo",
  "Titanium Man",
  "Unicorn",
  "Blizzard",
  "Whiplash",
  "Ghost",
  "Taskmaster",
  "Paladin",
  "Bushwacker",
  "Silver Sable",
  "Domino",
  "Shatterstar",
  "Feral",
  "Cannonball",
  "Sunspot",
  "Boom-Boom",
  "Warpath",
  "Strong Guy",
  "Multiple Man",
  "Siryn",
  "Polaris",
  "Havok",
  "Quicksilver",
  "Crystal",
  "Lockjaw",
  "Gorgon",
  "Karnak",
  "Triton",
  "Medusa",
  "Black Bolt",
  "Maximus",
  "Ronan",
  "Supreme Intelligence",
  "Captain Atlas",
  "Doctor Minerva",
  "Korath",
  "Yon-Rogg",
  "Minn-Erva",
  "Bron-Char",
  "Att-Lass",
  "Una-Rogg",
  "Talos",
  "Soren",
  "Norex",
  "Mar-Vell",
  "Genis-Vell",
  "Phyla-Vell",
  "Hulkling",
  "Wiccan",
  "Speed",
  "Patriot",
  "Stature",
  "Vision",
  "Jocasta",
  "Wonder Man",
  "Simon Williams",
  "Eric Williams",
  "Grim Reaper",
  "Swordsman",
  "Mantis",
  "Moondragon",
  "Drax",
  "Gamora",
  "Pip",
  "Adam Warlock",
  "Magus",
  "Goddess",
  "Thanos",
  "Mistress Death",
  "Chronos",
  "Mentor",
  "Starfox",
  "Isaac",
  "Eros",
  "Sui-San",
  "A'Lars",
  "Daina",
  "Demolition Man",
  "U.S. Agent",
  "Battlestar",
  "Lemuel",
  "Jack Flag",
  "Free Spirit",
  "Squirrel Girl",
  "Tippy-Toe",
  "Monkey Joe",
  "Doreen Green",
  "Nancy Whitehead",
  "Koi Boi",
  "Chipmunk Hunk",
  "Tombstone",
  "Hammerhead",
  "Silvermane",
  "Kingpin",
  "Vanessa Fisk",
  "Richard Fisk",
  "Rose",
  "Punisher",
  "Microchip",
  "Jigsaw",
  "Barracuda",
  "Ma Gnucci",
  "Russian",
  "Bushwacker",
  "Nuke",
  "Foolkiller",
  "Death Adder",
  "Anaconda",
  "Cobra",
  "Asp",
  "Cottonmouth",
  "Diamondback",
  "Princess Python",
  "Rock Python",
  "Puff Adder",
  "Coachwhip",
  "Boomslang",
  "Rattler",
  "Black Racer",
  "Fer-de-Lance",
  "Sidewinder",
  "King Cobra",
  "Bushmaster",
  "Death Adder",
  "Viper",
  "Madame Hydra",
  "Red Skull",
  "Baron Strucker",
  "Arnim Zola",
  "Crossbones",
  "Sin",
  "Taskmaster",
  "Batroc",
  "Zaran",
  "Machete",
  "Swordsman",
  "Black Knight",
  "Dane Whitman",
  "Sersi",
  "Ikaris",
  "Makkari",
  "Thena",
  "Gilgamesh",
  "Ajak",
  "Phastos",
  "Kingo",
  "Sprite",
  "Druig",
  "Kro",
  "Tiamut",
  "Arishem",
  "Jemiah",
  "Hargen",
  "Oneg",
  "Ziran",
  "Gammenon",
  "Tefral",
  "Nebulon",
  "Asa",
  "Eson",
  "Watcher",
  "Uatu",
  "Aron",
  "He Who Remains",
  "Kang",
  "Immortus",
  "Rama-Tut",
  "Scarlet Centurion",
  "Iron Lad",
  "Victor Timely",
  "Nathaniel Richards",
  "Ravonna",
  "Princess Ravonna",
  "Terminatrix",
  "Miss Minutes",
  "Hunter B-15",
  "Mobius",
  "Sylvie",
  "Loki",
  "Classic Loki",
  "Kid Loki",
  "Boastful Loki",
  "Alligator Loki",
  "President Loki",
  "Thor",
  "Lady Sif",
  "Warriors Three",
  "Volstagg",
  "Fandral",
  "Hogun",
  "Heimdall",
  "Odin",
  "Frigga",
  "Borre",
  "Tyr",
  "Balder",
  "Hermod",
  "Vidar",
  "Hoder",
  "Bragi",
  "Idunn",
  "Njord",
  "Frey",
  "Freya",
  "Skadi",
  "Ullr",
  "Forseti",
  "Syn",
  "Thrud",
  "Magni",
  "Modi",
  "Valkyries",
  "Brunnhilde",
  "Hilda",
  "Danielle",
  "Anastasia",
  "Regina",
  "Mist",
  "Karla",
  "Runa",
  "Hela",
  "Fenris",
  "Skrymir",
  "Ymir",
  "Surtur",
  "Kari",
  "Laufey",
  "Farbauti",
  "Angrboda",
  "Jormungand",
  "Sleipnir",
  "Hel-Horse",
  "Garm",
  "Hrym",
  "Thokk",
  "Nidhogg",
  "Ratatosk",
  "Vedfolnir",
  "Eikthyrnir",
  "Heidrun",
  "Vali",
  "Vidarr",
  "Hoenir",
  "Lodurr",
  "Mimir",
  "Bestla",
  "Borr",
  "Bur",
  "Buri",
  "Audhumla",
  "Ymir",
  "Thrudheim",
  "Bilskirnir",
  "Breidablik",
  "Gladsheim",
  "Valaskjalf",
  "Fensalir",
  "Noatun",
  "Himinbjorg",
  "Folkvang",
  "Sessrumnir",
  "Glitnir",
  "Landvidi",
  "Ydalir",
  "Alfheim",
  "Ljosalfar",
  "Svartalfheim",
  "Dokalfar",
  "Nidavellir",
  "Svartalfar",
  "Muspelheim",
  "Niflheim",
  "Hel",
  "Ginnungagap",
  "Yggdrasil",
  "Urd",
  "Verdandi",
  "Skuld",
  "Huginn",
  "Muninn",
  "Geri",
  "Freki",
  "Tanngrisnir",
  "Tanngnjostr",
  "Gulltoppr",
  "Hildisvini",
  "Skidbladnir",
  "Naglfar",
  "Hringhorni",
  "Gungnir",
  "Mjolnir",
  "Stormbreaker",
  "Hofund",
  "Draupnir",
  "Megingjord",
  "Jarngreipr",
  "Gram",
  "Tyrfing",
  "Skofnung",
  "Laevateinn",
  "Gleipnir",
  "Andvaranaut",
  "Brisingamen",
  "Necklace of Harmonia",
  "Cloak of Invisibility",
  "Apples of Idunn",
  "Mead of Poetry",
  "Horn of Gjallar",
  "Bifrost",
  "Rainbow Bridge",
  "Asgard",
  "Midgard",
  "Jotunheim",
  "Vanaheim",
  "Alfheim",
  "Svartalfheim",
  "Nidavellir",
  "Muspelheim",
  "Niflheim",
  "Helheim",
  "Valhalla",
  "Folkvangr",
  "Ragnarok",
  "Fimbulwinter",
  "Surtr",
  "Fenrir",
  "Jormungandr",
  "Hel",
  "Loki",
  "Thor",
  "Odin",
  "Freya",
  "Tyr",
  "Heimdall",
  "Frigg",
  "Baldr",
  "Hodr",
  "Nanna",
  "Forseti",
  "Idunn",
  "Bragi",
  "Sif",
  "Magni",
  "Modi",
  "Thrud",
  "Ullr",
  "Vidar",
  "Vali",
  "Hermod",
  "Skadi",
  "Njord",
  "Frey",
  "Freya",
  "Gerdr",
  "Skirnir",
  "Byggvir",
  "Beyla",
  "Lofn",
  "Syn",
  "Var",
  "Vor",
  "Snotra",
  "Hlin",
  "Sjofn",
  "Eir",
  "Gefjon",
  "Fulla",
  "Gna",
  "Irpa",
  "Thorpe",
  "Saga",
  "Himinglaeva",
  "Duva",
  "Bylgja",
  "Hronn",
  "Kolga",
  "Unn",
  "Blodughadda",
  "Bara",
  "Hefring",
  "Drofn",
  "Ran",
  "Aegir",
  "Nine Daughters",
  "Gymir",
  "Aurboda",
  "Angrboda",
  "Jarnsaxa",
  "Greip",
  "Hyrrokkin",
  "Thokk",
  "Loki's Children",
  "Narfi",
  "Vali",
  "Sleipnir",
  "Fenrir",
  "Jormungandr",
  "Hel",
  "Eingana",
  "Sinmara",
  "Glut",
  "Eimnir",
  "Eggther",
  "Fjolnir",
  "Gangleri",
  "Har",
  "Jafnhar",
  "Thridi",
  "Bolverk",
  "Grimnir",
  "Gondlir",
  "Herjan",
  "Hjalmberi",
  "Thekk",
  "Thror",
  "Thrudr",
  "Udr",
  "Yggr",
  "Alfodr",
  "Atandri",
  "Bifidi",
  "Bileyg",
  "Balki",
  "Bileygr",
  "Fjolnir",
  "Glapsvidir",
  "Gondul",
  "Harbard",
  "Hnikar",
  "Skoll",
  "Hati",
  "Managarm",
  "Skalli",
  "Fenris",
  "Garm",
  "Tyr",
  "Zan",
  "Hild",
  "Goll",
  "Geirrod",
  "Thjazi",
  "Skadi",
  "Njord",
  "Freyja",
  "Odr",
  "Hildisvini",
  "Gullveig",
  "Heid",
  "Angrboda",
  "Iron Wood",
  "Vargr",
  "Varg",
  "Vargur",
  "Vargynja",
  "Ulfhednar",
  "Berserker",
  "Einherjar",
  "Valkyrie",
  "Shieldmaiden",
  "Amazon",
  "Wonder Woman",
  "Diana Prince",
  "Steve Trevor",
  "Etta Candy",
  "Hippolyta",
  "Antiope",
  "Artemis",
  "Cheetah",
  "Ares",
  "Circe",
  "Doctor Psycho",
  "Giganta",
  "Silver Swan",
  "Veronica Cale",
  "Maxwell Lord",
  "Barbara Minerva",
  "Cassandra Sandsmark",
  "Donna Troy",
  "Superman",
  "Clark Kent",
  "Lois Lane",
  "Jimmy Olsen",
  "Perry White",
  "Lex Luthor",
  "Brainiac",
  "General Zod",
  "Darkseid",
  "Batman",
  "Bruce Wayne",
  "Alfred",
  "Gordon",
  "Robin",
  "Dick Grayson",
  "Jason Todd",
  "Tim Drake",
  "Damian Wayne",
  "Batgirl",
  "Barbara Gordon",
  "Oracle",
  "Nightwing",
  "Red Hood",
  "Red Robin",
  "Spoiler",
  "Cassandra Cain",
  "Stephanie Brown",
  "Huntress",
  "Helena Bertinelli",
  "Catwoman",
  "Selina Kyle",
  "Penguin",
  "Oswald Cobblepot",
  "Riddler",
  "Edward Nygma",
  "Two-Face",
  "Harvey Dent",
  "Joker",
  "Harley Quinn",
  "Poison Ivy",
  "Pamela Isley",
  "Mr. Freeze",
  "Victor Fries",
  "Scarecrow",
  "Jonathan Crane",
  "Bane",
  "Ra's al Ghul",
  "Talia al Ghul",
  "Deathstroke",
  "Slade Wilson",
  "Deadshot",
  "Floyd Lawton",
  "Captain Boomerang",
  "Killer Croc",
  "Waylon Jones",
  "Clayface",
  "Basil Karlo",
  "Mad Hatter",
  "Jervis Tetch",
  "Black Mask",
  "Roman Sionis",
  "Hush",
  "Thomas Elliot",
  "Firefly",
  "Garfield Lynns",
  "Killer Moth",
  "Calendar Man",
  "Clock King",
  "Condiment King",
  "Crazy Quilt",
  "Polka-Dot Man",
  "Kite Man",
  "Hell Yeah",
  "Ventriloquist",
  "Scarface",
  "Professor Pyg",
  "Flamingo",
  "Victor Zsasz",
  "Hugo Strange",
  "Carmine Falcone",
  "Sal Maroni",
  "Alberto Falcone",
  "Sofia Gigante",
  "Black Canary",
  "Green Arrow",
  "Oliver Queen",
  "Dinah Lance",
  "Roy Harper",
  "Speedy",
  "Arsenal",
  "Red Arrow",
  "Connor Hawke",
  "Mia Dearden",
  "Emiko Queen",
  "Flash",
  "Barry Allen",
  "Wally West",
  "Jay Garrick",
  "Bart Allen",
  "Iris West",
  "Nora West-Allen",
  "Eobard Thawne",
  "Reverse Flash",
  "Zoom",
  "Hunter Zolomon",
  "Godspeed",
  "Savitar",
  "Cobalt Blue",
  "Inertia",
  "Captain Cold",
  "Leonard Snart",
  "Heat Wave",
  "Mick Rory",
  "Golden Glider",
  "Lisa Snart",
  "Mirror Master",
  "Sam Scudder",
  "Weather Wizard",
  "Mark Mardon",
  "Trickster",
  "James Jesse",
  "Axel Walker",
  "Pied Piper",
  "Hartley Rathaway",
  "Top",
  "Roscoe Dillon",
  "Captain Boomerang",
  "Digger Harkness",
  "Owen Mercer",
  "Green Lantern",
  "Hal Jordan",
  "John Stewart",
  "Guy Gardner",
  "Kyle Rayner",
  "Alan Scott",
  "Jessica Cruz",
  "Simon Baz",
  "Sinestro",
  "Atrocitus",
  "Larfleeze",
  "Saint Walker",
  "Indigo-1",
  "Star Sapphire",
  "Carol Ferris",
  "Aquaman",
  "Arthur Curry",
  "Mera",
  "Ocean Master",
  "Orm",
  "Black Manta",
  "David Hyde",
  "Aqualad",
  "Garth",
  "Tempest",
  "Kaldur'ahm",
  "Jackson Hyde",
  "Tula",
  "Aquagirl",
  "Dolphin",
  "Lagoon Boy",
  "Hawkman",
  "Carter Hall",
  "Hawkgirl",
  "Kendra Saunders",
  "Shayera Hol",
  "Atom",
  "Ray Palmer",
  "Ryan Choi",
  "Firestorm",
  "Ronnie Raymond",
  "Martin Stein",
  "Jason Rusch",
  "Jefferson Jackson",
  "Blue Beetle",
  "Ted Kord",
  "Jaime Reyes",
  "Dan Garrett",
  "Zatanna",
  "John Constantine",
  "Swamp Thing",
  "Alec Holland",
  "Abby Arcane",
  "Animal Man",
  "Buddy Baker",
  "Starfire",
  "Koriand'r",
  "Raven",
  "Rachel Roth",
  "Beast Boy",
  "Garfield Logan",
  "Cyborg",
  "Victor Stone",
  "Nightwing",
  "Robin",
  "Superboy",
  "Kon-El",
  "Jon Kent",
  "Supergirl",
  "Kara Zor-El",
  "Power Girl",
  "Karen Starr",
  "Steel",
  "John Henry Irons",
  "Martian Manhunter",
  "J'onn J'onzz",
  "Miss Martian",
  "M'gann M'orzz",
  "Legion of Super-Heroes",
  "Brainiac 5",
  "Saturn Girl",
  "Cosmic Boy",
  "Lightning Lad",
  "Mon-El",
  "Shadow Lass",
  "Phantom Girl",
  "Chameleon Boy",
  "Colossal Boy",
  "Shrinking Violet",
  "Bouncing Boy",
  "Triplicate Girl",
  "Element Lad",
  "Dream Girl",
  "Star Boy",
  "Ultra Boy",
  "Invisible Kid",
  "Matter-Eater Lad",
  "Timber Wolf",
  "Chemical King",
  "Karate Kid",
  "Princess Projectra",
  "Ferro Lad",
  "Dawnstar",
  "Wildfire",
  "Tyroc",
  "Blok",
  "White Witch",
  "Tellus",
  "Quislet",
  "Polar Boy",
  "Infectious Lass",
  "Catspaw",
  "Dragonmage",
  "Kono",
  "Flederweb",
  "Veilmist",
  "Computo",
  "Darkseid",
  "Granny Goodness",
  "Desaad",
  "Kalibak",
  "Steppenwolf",
  "Mantis",
  "Parademons",
  "Female Furies",
  "Big Barda",
  "Mister Miracle",
  "Scott Free",
  "Oberon",
  "Orion",
  "Lightray",
  "Highfather",
  "Metron",
  "Forever People",
  "Beautiful Dreamer",
  "Vykin",
  "Mark Moonrider",
  "Serifan",
  "Infinity Man",
  "New Gods",
  "Apokolips",
  "New Genesis",
  "Source",
  "Anti-Life",
  "Omega Beams",
  "Mother Box",
  "Father Box",
  "Boom Tube",
  "Astro-Force",
  "Hunger Dogs",
  "Lowlies",
  "Deep Six",
  "Sleez",
  "Amazing Grace",
  "Glorious Godfrey",
  "Doctor Bedlam",
  "Vundabar",
  "Kanto",
  "Gilotina",
  "Lashina",
  "Stompa",
  "Mad Harriet",
  "Bernadeth",
  "Artemiz",
  "Speed Queen",
  "Bloody Mary",
  "Tigra",
  "Malice Vundabar",
  "Chessure",
  "Red Devil",
  "Blue Devil",
  "Etrigan",
  "Jason Blood",
  "Merlin",
  "Madame Xanadu",
  "Deadman",
  "Boston Brand",
  "Spectre",
  "Jim Corrigan",
  "Hal Jordan",
  "Crispus Allen",
  "Phantom Stranger",
  "Pandora",
  "Question",
  "Vic Sage",
  "Renee Montoya",
  "Doctor Fate",
  "Kent Nelson",
  "Hector Hall",
  "Khalid Nassour",
  "Nabu",
  "Helmet of Fate",
  "Amulet of Anubis",
  "Cloak of Destiny",
  "Sandman",
  "Dream",
  "Morpheus",
  "Death",
  "Destiny",
  "Destruction",
  "Desire",
  "Despair",
  "Delirium",
  "Endless",
  "Lucifer Morningstar",
  "Mazikeen",
  "Amenadiel",
  "Uriel",
  "Michael Demiurgos",
  "Gabriel",
  "Remiel",
  "Duma",
  "Sandman",
  "Wesley Dodds",
  "Garrett Sanford",
  "Hector Hall",
  "Daniel Hall",
  "Kieran Marshall",
  "Sandy Hawkins",
  "Sanderson Hawkins",
  "Silicon",
  "Prophet",
  "Brute",
  "Glob",
  "Dreamstone",
  "Nightmare",
  "Corinthian",
  "Fiddler's Green",
  "Merv Pumpkinhead",
  "Lucien",
  "Cain",
  "Abel",
  "Eve",
  "Matthew the Raven",
  "Gault",
  "Rose Walker",
  "Jed Walker",
  "Lyta Hall",
  "Hippolyta Trevor",
  "Fury",
  "Hector Hall",
  "Sandman",
  "Daniel Hall",
  "Dream",
  "Unity Kinkaid",
  "Miranda Walker",
  "Desire",
  "Barnaby",
  "Clarice",
  "Johan",
  "Zorina",
  "Faustin",
  "Hal Carter",
  "Kenny",
  "Chantal",
  "Zorina",
  "Stefan",
  "Barnabas",
  "Destruction",
  "Olethros",
  "Ishtar",
  "Bast",
  "Delirium",
  "Delight",
  "Barnaby",
  "Destiny",
  "Book of Destiny",
  "Death",
  "Ankh",
  "Didi",
  "Teleute",
  "Lucifer",
  "Morningstar",
  "Samael",
  "Lightbringer",
  "Mazikeen",
  "Lilith",
  "Beelzebub",
  "Asmodeus",
  "Belial",
  "Duma",
  "Remiel",
  "Saraquael",
  "Raguel",
  "Michael",
  "Gabriel",
  "Uriel",
  "Raphael",
  "Zadkiel",
  "Jophiel",
  "Chamuel",
  "Haniel",
  "Presence",
  "Voice",
  "Hand",
  "Elaine Belloc",
  "Mona",
  "Gail",
  "Madge",
  "Hob Gadling",
  "Death of the Endless",
  "Dream of the Endless",
  "Destruction of the Endless",
  "Desire of the Endless",
  "Despair of the Endless",
  "Delirium of the Endless",
  "Destiny of the Endless",
  "The Endless",
  "The Kindly Ones",
  "The Fates",
  "The Furies",
  "Clotho",
  "Lachesis",
  "Atropos",
  "Norns",
  "Urd",
  "Verdandi",
  "Skuld",
  "Moirai",
  "Parcae",
  "Fates",
  "Weird Sisters",
  "Three Witches",
  "Mildred",
  "Mordred",
  "Cynthia",
  "Thessaly",
  "Larissa",
  "Wanda",
  "Zatanna Zatara",
  "Giovanni Zatara",
  "Sindella",
  "Doctor Occult",
  "Rose Psychic",
  "Tim Hunter",
  "Books of Magic",
  "John Constantine",
  "Hellblazer",
  "Swamp Thing",
  "Abby Holland",
  "Tefe Holland",
  "Anton Arcane",
  "Patchwork Man",
  "Matthew Cable",
  "Floronic Man",
  "Jason Woodrue",
  "Poison Ivy",
  "Alec Holland",
  "Linda Holland",
  "Parliament of Trees",
  "Sprout",
  "Yggdrasil",
  "The Green",
  "The Red",
  "The Clear",
  "The Grey",
  "The Rot",
  "The Black",
  "The Divided",
  "The Metal",
  "The Melt",
  "Animal Man",
  "Buddy Baker",
  "Ellen Baker",
  "Cliff Baker",
  "Maxine Baker",
  "Socks",
  "The Red",
  "Avatar",
  "Totems",
  "Spider",
  "Hawk",
  "Snake",
  "Shark",
  "Wolf",
  "Eagle",
  "Bear",
  "Salmon",
  "Life Web",
  "Red Plague",
  "Hunters Three",
  "Anton Arcane",
  "Dark Avatar",
  "Sethe",
  "Un-Men",
  "Cranius",
  "Ophidian",
  "Peraxxus",
  "Shepherd",
  "Brother Blood",
  "Trigon",
  "Arella",
  "Raven",
  "Azarath",
  "Brotherhood of Evil",
  "Brain",
  "Monsieur Mallah",
  "Madame Rouge",
  "General Immortus",
  "Garguax",
  "Doom Patrol",
  "Chief",
  "Niles Caulder",
  "Robotman",
  "Cliff Steele",
  "Elasti-Girl",
  "Rita Farr",
  "Negative Man",
  "Larry Trainor",
  "Mento",
  "Steve Dayton",
  "Beast Boy",
  "Celsius",
  "Arani Desai",
  "Tempest",
  "Joshua Clay",
  "Negative Woman",
  "Valentina Vostok",
  "Dorothy Spinner",
  "Crazy Jane",
  "Kay Challis",
  "Danny the Street",
  "Flex Mentallo",
  "Kate Godwin",
  "Coagula",
  "Rebis",
  "Legion of Super-Heroes",
  "Superboy",
  "Supergirl",
  "Mon-El",
  "Shadow Lass",
  "Brainiac 5",
  "Querl Dox",
  "Supergirl",
  "Kara Zor-El",
  "Linda Danvers",
  "Matrix",
  "Power Girl",
  "Kara Zor-L",
  "Tanya Spears",
  "Steel",
  "Natasha Irons",
  "John Henry Irons",
  "Teen Titans",
  "Robin",
  "Kid Flash",
  "Wonder Girl",
  "Aqualad",
  "Speedy",
  "Starfire",
  "Raven",
  "Beast Boy",
  "Cyborg",
  "Terra",
  "Markovia",
  "Brion Markov",
  "Geo-Force",
  "Tara Markov",
  "Deathstroke",
  "Slade Wilson",
  "Rose Wilson",
  "Ravager",
  "Jericho",
  "Joseph Wilson",
  "Adeline Kane",
  "Grant Wilson",
  "Wintergreen",
  "Billy Wintergreen",
  "H.I.V.E.",
  "Queen Bee",
  "Mammoth",
  "Shimmer",
  "Psimon",
  "Gizmo",
  "Jinx",
  "Fearsome Five",
  "Doctor Light",
  "Arthur Light",
  "Neutron",
  "Bolt",
  "Warp",
  "Plasmus",
  "Trident",
  "Cinder",
  "Overload",
  "Brother Blood",
  "Mother Mayhem",
  "Deathstroke",
  "Titans East",
  "Cyborg",
  "Bumblebee",
  "Speedy",
  "Mas y Menos",
  "Jericho",
  "Ravager",
  "Batgirl",
  "Kid Devil",
  "Miss Martian",
  "Blue Beetle",
  "Static",
  "Gear",
  "Rocket",
  "Icon",
  "Hardware",
  "Blood Syndicate",
  "Wise Son",
  "Fade",
  "Brickhouse",
  "Third Rail",
  "DMZ",
  "Flashback",
  "Aquamaria",
  "Kobalt",
  "Xombi",
  "Shadow Cabinet",
  "Icon",
  "Rocket",
  "Hardware",
  "Superboy",
  "Steel",
  "Eradicator",
  "Cyborg Superman",
  "Hank Henshaw",
  "Mongul",
  "Doomsday",
  "Bizarro",
  "Metallo",
  "John Corben",
  "Parasite",
  "Rudy Jones",
  "Toyman",
  "Winslow Schott",
  "Livewire",
  "Leslie Willis",
  "Silver Banshee",
  "Siobhan McDougal",
  "Volcana",
  "Luminus",
  "Barrage",
  "Riot",
  "Maxima",
  "Draaga",
  "Lobo",
  "Main Man",
  "Czarnia",
  "Space Dolphins",
  "Space Hogs",
  "Frag",
  "Vril Dox",
  "L.E.G.I.O.N.",
  "Stealth",
  "Strata",
  "Garv",
  "Phase",
  "Telepath",
  "Captain Comet",
  "Adam Blake",
  "Lady Quark",
  "Lord Volt",
  "Pariah",
  "Harbinger",
  "Lyla",
  "Monitor",
  "Anti-Monitor",
  "Mobius",
  "Alexander Luthor",
  "Earth-3",
  "Ultraman",
  "Superwoman",
  "Owlman",
  "Johnny Quick",
  "Power Ring",
  "Crime Syndicate",
  "Syndicate",
  "CSA",
  "Justice Underground",
  "Quizmaster",
  "Lady Sonar",
  "General Grodd",
  "Sir Solomon Grundy",
  "Q-Ranger",
  "Justice League",
  "Superman",
  "Batman",
  "Wonder Woman",
  "Flash",
  "Green Lantern",
  "Aquaman",
  "Martian Manhunter",
  "Cyborg",
  "Shazam",
  "Hawkman",
  "Hawkgirl",
  "Green Arrow",
  "Black Canary",
  "Atom",
  "Firestorm",
  "Zatanna",
  "Doctor Fate",
  "Spectre",
  "Phantom Stranger",
  "Swamp Thing",
  "Deadman",
  "Etrigan",
  "Lobo",
  "Starfire",
  "Raven",
  "Beast Boy",
  "Blue Beetle",
  "Booster Gold",
  "Captain Atom",
  "Fire",
  "Ice",
  "Vixen",
  "Vibe",
  "Gypsy",
  "Steel",
  "Commander Steel",
  "Doctor Light",
  "Kimiyo Hoshi",
  "Katana",
  "Geo-Force",
  "Metamorpho",
  "Black Lightning",
  "Looker",
  "Halo",
  "Windfall",
  "Fury",
  "Obsidian",
  "Jade",
  "Northwind",
  "Brainwave Jr.",
  "Sand",
  "Silver Scarab",
  "Hector Hall",
  "Lyta Trevor",
  "Nuklon",
  "Atom Smasher",
  "Hourman",
  "Rick Tyler",
  "Wildcat",
  "Yolanda Montez",
  "Doctor Mid-Nite",
  "Charles McNider",
  "Pieter Cross",
  "Mister Terrific",
  "Terry Sloane",
  "Michael Holt",
  "Crimson Avenger",
  "Lee Travis",
  "Jill Carlyle",
  "Wing",
  "Speedy",
  "Green Arrow",
  "Arsenal",
  "Red Arrow",
  "Connor Hawke",
  "Shado",
  "Merlyn",
  "Komodo",
  "Count Vertigo",
  "Brick",
  "Deathstroke",
  "Deadshot",
  "Captain Boomerang",
  "Clock King",
  "Onomatopoeia",
  "Prometheus",
  "Talia al Ghul",
  "League of Assassins",
  "Ra's al Ghul",
  "Ubu",
  "Lady Shiva",
  "Cassandra Cain",
  "David Cain",
  "Bronze Tiger",
  "Richard Dragon",
  "Question",
  "Huntress",
  "Nightwing",
  "Oracle",
  "Batgirl",
  "Robin",
  "Red Hood",
  "Red Robin",
  "Spoiler",
  "Black Bat",
  "Bluebird",
  "Signal",
  "Duke Thomas",
  "Gotham Girl",
  "Gotham",
  "Claire Clover",
  "Hank Clover",
  "Batman Who Laughs",
  "Grim Knight",
  "Dark Knights",
  "Devastator",
  "Murder Machine",
  "Red Death",
  "Dawnbreaker",
  "Drowned",
  "Merciless",
  "Barbatos",
  "Court of Owls",
  "Talon",
  "Lincoln March",
  "Thomas Wayne",
  "Martha Wayne",
  "Joe Chill",
  "Joker",
  "Harley Quinn",
  "Punchline",
  "Alexis Kaye",
  "Three Jokers",
  "Criminal",
  "Comedian",
  "Clown",
  "Jack Napier",
  "Arthur Fleck",
  "Penguin",
  "Riddler",
  "Catwoman",
  "Poison Ivy",
  "Scarecrow",
  "Bane",
  "Killer Croc",
  "Clayface",
  "Mad Hatter",
  "Mr. Freeze",
  "Firefly",
  "Hugo Strange",
  "Professor Pyg",
  "Flamingo",
  "Black Mask",
  "Victor Zsasz",
  "Hush",
  "Calendar Man",
  "Killer Moth",
  "Ventriloquist",
  "Scarface",
  "Tweedledee",
  "Tweedledum",
  "Baby Doll",
  "Mary Dahl",
  "Clock King",
  "Condiment King",
  "Crazy Quilt",
  "Polka-Dot Man",
  "Kite Man",
  "Carpenter",
  "Jenna Duffy",
  "Film Freak",
  "Burt Weston",
  "Fright",
  "Linda Friitawa",
  "Electrocutioner",
  "Maxie Zeus",
  "Anarky",
  "Lonnie Machin",
  "Ulysses Armstrong",
  "Prometheus",
  "Chad Graham",
  "Curtis Base",
  "Onomatopoeia",
  "KGBeast",
  "Anatoli Knyazev",
  "Deadshot",
  "Deathstroke",
  "Merlyn",
  "Dark Archer",
  "Komodo",
  "Robert Queen",
  "Shrapnel",
  "Mark Scheffer",
  "Copperhead",
  "Larvan",
  "Brie Larvan",
  "Bug-Eyed Bandit",
  "Calculator",
  "Noah Kuttler",
  "Oracle",
  "Penguin's Umbrella",
  "Black Spider",
  "Eric Needham",
  "Derrick Coe",
  "Johnny LaMonica",
  "Cluemaster",
  "Arthur Brown",
  "Stephanie Brown",
  "Crystal Brown",
  "Ratcatcher",
  "Otis Flannegan",
  "Pigeon Person",
  "Dove Bailey",
  "Sewer King",
  "Jazzman",
  "Jimmy Peake",
  "Lock-Up",
  "Lyle Bolton",
  "Ferak",
  "Temblor",
  "Rumble",
  "Nitro",
  "Condor",
  "Falcon",
  "Hawk",
  "Owl",
  "Vulture",
  "Condor",
  "Raptor",
  "Nightbird",
  "Black Condor",
  "Firehawk",
  "Lorraine Reilly",
  "Golden Eagle",
  "Charley Parker",
  "Northwind",
  "Norda",
  "Hawk",
  "Dove",
  "Deadman",
  "Spectre",
  "Doctor Fate",
  "Hourman",
  "Starman",
  "Sandman",
  "Wildcat",
  "Atom",
  "Doctor Mid-Nite",
  "Mister Terrific",
  "Flash",
  "Jay Garrick",
  "Alan Scott",
  "Green Lantern",
  "Sentinel",
  "Jade",
  "Obsidian",
  "Stargirl",
  "S.T.R.I.P.E.",
  "Pat Dugan",
  "Courtney Whitmore",
  "Star-Spangled Kid",
  "Shiv",
  "Cindy Burman",
  "Dragon King",
  "Ultra-Humanite",
  "Per Degaton",
  "Vandal Savage",
  "Solomon Grundy",
  "Eclipso",
  "Shade",
  "Gentleman Ghost",
  "Rag Doll",
  "Icicle",
  "Joar Mahkent",
  "Cameron Mahkent",
  "Captain Cold",
  "Heat Wave",
  "Mirror Master",
  "Weather Wizard",
  "Trickster",
  "Pied Piper",
  "Golden Glider",
  "Top",
  "Captain Boomerang",
  "Abra Kadabra",
  "Grodd",
  "Gorilla Grodd",
  "King Shark",
  "Nanaue",
  "Human Flying Fish",
  "Lagoon Boy",
  "Devil Ray",
  "Black Manta",
  "Ocean Master",
  "Siren",
  "Hila",
  "Fisherman",
  "Scavenger",
  "Demon Gate",
  "Atlantis",
  "Themyscira",
  "Paradise Island",
  "Amazon",
  "Wonder Woman",
  "Hippolyta",
  "Philippus",
  "Mala",
  "Artemis",
  "Nubia",
  "Fury",
  "Donna Troy",
  "Wonder Girl",
  "Cassie Sandsmark",
  "Yara Flor",
  "Future State",
  "Trinity",
  "Superman",
  "Batman",
  "Wonder Woman",
  "Justice League",
  "Darkseid",
  "Steppenwolf",
  "Desaad",
  "Granny Goodness",
  "Kalibak",
  "Orion",
  "Lightray",
  "Big Barda",
  "Mister Miracle",
  "Highfather",
  "Metron",
  "Forever People",
  "New Gods",
  "Source Wall",
  "Prometheus",
  "Anti-Life Equation",
  "Omega Effect",
  "Astro-Force",
  "Mother Box",
  "Father Box",
  "Boom Tube",
  "Apokolips",
  "New Genesis",
  "Fourth World",
  "Jack Kirby",
  "Mister Miracle",
  "Scott Free",
  "Big Barda",
  "Oberon",
  "Shilo Norman",
  "Funky Flashman",
  "Sonny Sumo",
  "Mother Box",
  "Himmon",
  "Seraphim",
  "Infinity Man",
  "Beautiful Dreamer",
  "Vykin the Black",
  "Mark Moonrider",
  "Serifan",
  "Big Bear",
  "Orion",
  "Lightray",
  "Forager",
  "Primus",
  "Lonars",
  "Tigra",
  "Jezebelle",
  "Seagrin",
  "Fastbak",
  "Vundabar",
  "Kanto",
  "Desaad",
  "Kalibak",
  "Steppenwolf",
  "Mantis",
  "Amazing Grace",
  "Glorious Godfrey",
  "Doctor Bedlam",
  "Granny Goodness",
  "Female Furies",
  "Big Breeda",
  "Gilotina",
  "Lashina",
  "Stompa",
  "Mad Harriet",
  "Bernadeth",
  "Artemiz",
  "Bloody Mary",
  "Speed Queen",
  "Malice Vundabar",
  "Chessure",
  "Tigra",
  "Darkseid",
  "Uxas",
  "Yuga Khan",
  "Heggra",
  "Tiggra",
  "Suli",
  "Kalibak",
  "Orion",
  "Grayven",
  "Deathspawn",
  "Parademons",
  "Deep Six",
  "Slig",
  "Trokte",
  "Gole",
  "Jaffar",
  "Pyron",
  "Shale",
  "Intergang",
  "Bruno Mannheim",
  "Whisper A'Daire",
  "Kyle Abbot",
  "Black Lightning",
  "Jefferson Pierce",
  "Anissa Pierce",
  "Thunder",
  "Jennifer Pierce",
  "Lightning",
  "Painkiller",
  "Khalil Payne",
  "Grace Choi",
  "Wylde",
  "Tobias Whale",
  "100",
  "Syndicate",
  "Masters of Disaster",
  "New Wave",
  "Heatstroke",
  "Coldsnap",
  "Shakedown",
  "Windfall",
  "Looker",
  "Halo",
  "Geo-Force",
  "Katana",
  "Outsiders",
  "Batman",
  "Black Lightning",
  "Metamorpho",
  "Katana",
  "Geo-Force",
  "Halo",
  "Looker",
  "Windfall",
  "Techno",
  "Wylde",
  "Faust",
  "Sebastian Faust",
  "Cinder",
  "Carla Moretti",
  "Atomic Knight",
  "Gardner Grayle",
  "Major Force",
  "Clifford Zmeck",
  "Captain Atom",
  "Nathaniel Adam",
  "Plastique",
  "Bette Sans Souci",
  "General Eiling",
  "Wade Eiling",
  "Queen Bee",
  "Zazzala",
  "Blue Beetle",
  "Dan Garrett",
  "Ted Kord",
  "Jaime Reyes",
  "Khaji Da",
  "Reach",
  "Scarab",
  "Black Beetle",
  "Green Beetle",
  "B'arzz Ooom",
  "Milagro Reyes",
  "Alberto Reyes",
  "Bianca Reyes",
  "Brenda",
  "Paco",
  "Nadia",
  "La Dama",
  "Amparo Cardenas",
  "Brenda's Aunt",
  "Peacemaker",
  "Christopher Smith",
  "Flag",
  "Rick Flag",
  "Waller",
  "Amanda Waller",
  "Task Force X",
  "Suicide Squad",
  "Deadshot",
  "Harley Quinn",
  "Captain Boomerang",
  "Killer Croc",
  "Enchantress",
  "Katana",
  "El Diablo",
  "Slipknot",
  "King Shark",
  "Bronze Tiger",
  "Count Vertigo",
  "Punch",
  "Jewelee",
  "Mindboggler",
  "Chronos",
  "David Clinton",
  "Blockbuster",
  "Roland Desmond",
  "Mark Desmond",
  "Nightshade",
  "Eve Eden",
  "Nemesis",
  "Tom Tresser",
  "Sarge Steel",
  "Checkmate",
  "King",
  "Queen",
  "Knight",
  "Bishop",
  "Rook",
  "Pawn",
  "Maxwell Lord",
  "Lord Industries",
  "OMAC",
  "Brother Eye",
  "Kevin Kho",
  "Sasha Bordeaux",
  "Mister Bones",
  "Director Bones",
  "Jade",
  "Jennie-Lynn Hayden",
  "Obsidian",
  "Todd Rice",
  "Infinity Inc.",
  "Skyman",
  "Sylvester Pemberton",
  "Star-Spangled Kid",
  "Pat Dugan",
  "S.T.R.I.P.E.",
  "Fury",
  "Lyta Trevor",
  "Hippolyta Trevor",
  "Hector Hall",
  "Silver Scarab",
  "Sandman",
  "Nuklon",
  "Albert Rothstein",
  "Atom Smasher",
  "Hourman",
  "Rick Tyler",
  "Miraclo",
  "Wildcat",
  "Yolanda Montez",
  "Ted Grant",
  "Doctor Mid-Nite",
  "Beth Chapel",
  "Charles McNider",
  "Pieter Cross",
  "Brainwave Jr.",
  "Henry King Jr.",
  "Northwind",
  "Norda",
  "Hawk",
  "Hawkman",
  "Carter Hall",
  "Shiera Sanders",
  "Kendra Saunders",
  "Shayera Thal",
  "Hath-Set",
  "Nth Metal",
  "Thanagarian",
  "Absorbacron",
  "Byth",
  "Paragon",
  "Golden Eagle",
  "Charley Parker",
  "Fel Andar",
  "Spy Smasher",
  "Katar Hol",
  "Shayera Hol",
  "Hawk",
  "Dove",
  "Don Hall",
  "Dawn Granger",
  "Holly Granger",
  "Deadman",
  "Boston Brand",
  "Rama Kushna",
  "Nanda Parbat",
  "Spectre",
  "Aztar",
  "Voice of the Presence",
  "Wrath of God",
  "Jim Corrigan",
  "Hal Jordan",
  "Crispus Allen",
  "Madame Xanadu",
  "Nimue",
  "Phantom Stranger",
  "Judas Iscariot",
  "Wandering Jew",
  "Voice",
  "Council of Wizards",
  "Doctor Occult",
  "Rose Psychic",
  "Seven Soldiers",
  "Zatanna",
  "Homo Magi",
  "John Zatara",
  "Sindella",
  "Giovanni Zatara",
  "Backward Magic",
  "Logomancy",
  "Etrigan",
  "Jason Blood",
  "Merlin",
  "Camelot",
  "Demon",
  "Rhyme of Eternity",
  "Gone! Gone! -- the form of man -- Rise the demon Etrigan!",
  "Belial",
  "Scapegoat",
  "Lady Smersh",
  "Klarion the Witch Boy",
  "Teekl",
  "Limbo Town",
  "Roanoke",
  "Submissionaires",
  "Sheeda",
  "Nebuchadnezzar",
  "Morrison",
  "Mister Melmoth",
  "Gloriana Tenebrae",
  "Castle Revolving",
  "Queen of Afar",
  "Seven Unknown Men",
  "Frankenstein",
  "Bride",
  "S.H.A.D.E.",
  "Father Time",
  "Ray Palmer",
  "Super Hero Agency for Defense and Enforcement",
  "Animal Man",
  "Buddy Baker",
  "Life Force",
  "Morphogenetic Field",
  "The Red",
  "Maxine Baker",
  "Cliff Baker",
  "Ellen Baker",
  "Socks the Cat",
  "A",
  "Swamp Thing",
  "The Green",
  "Parliament of Trees",
  "The Rot",
  "Anton Arcane",
  "Abby Arcane",
  "Tefe Holland",
  "John Constantine",
  "Hellblazer",
  "Laughing Magician",
  "Master of the Dark Arts",
  "Synchronicity Wave",
  "Chas Chandler",
  "Renee Chandler",
  "Geraldine Chandler",
  "Trish Chandler",
  "Zed",
  "Mary Martin",
  "Emma",
  "Gemma Masters",
  "Mercury",
  "Richie Simpson",
  "Papa Midnite",
  "Manga Khan",
  "L-Ron",
  "Justice League International",
  "Maxwell Lord",
  "Blue Beetle",
  "Ted Kord",
  "Booster Gold",
  "Michael Jon Carter",
  "Skeets",
  "Rip Hunter",
  "Time Masters",
  "Waverider",
  "Matthew Ryder",
  "Linear Men",
  "Hunter",
  "Liri Lee",
  "Corky Baxter",
  "Danette Reilly",
  "Firebrand",
  "Guy Gardner",
  "Green Lantern",
  "G'Nort",
  "Kilowog",
  "Arisia",
  "Ch'p",
  "B'dg",
  "Ice",
  "Tora Olafsdotter",
  "Fire",
  "Beatriz da Costa",
  "Green Flame",
  "Vixen",
  "Mari McCabe",
  "Tantu Totem",
  "Anansi",
  "Animal Spirits",
  "Vibe",
  "Paco Ramone",
  "Vibrational Powers",
  "Gypsy",
  "Cindy Reynolds",
  "Illusion Casting",
  "Steel",
  "Hank Heywood III",
  "Commander Steel",
  "Hank Heywood",
  "Doctor Mid-Nite",
  "Charles McNider",
  "Beth Chapel",
  "Pieter Cross",
  "Mister Terrific",
  "Terry Sloane",
  "Michael Holt",
  "Fair Play",
  "T-Spheres",
  "Doctor Fate",
  "Kent Nelson",
  "Inza Cramer",
  "Eric Strauss",
  "Linda Strauss",
  "Hector Hall",
  "Khalid Ben-Hassin",
  "Khalid Nassour",
  "Nabu",
  "Tower of Fate",
  "Salem",
  "Helmet",
  "Amulet",
  "Cloak",
  "Sandman",
  "Wesley Dodds",
  "Gas Mask",
  "Sanderson Hawkins",
  "Sandy the Golden Boy",
  "Silica Powers",
  "Garrett Sanford",
  "Brute and Glob",
  "Hector Hall",
  "Lyta Hall",
  "Daniel Hall",
  "Dream",
  "Justice Society",
  "JSA",
  "Golden Age",
  "Jay Garrick",
  "Flash",
  "Alan Scott",
  "Green Lantern",
  "Carter Hall",
  "Hawkman",
  "Shiera Sanders",
  "Hawkgirl",
  "Ted Grant",
  "Wildcat",
  "Charles McNider",
  "Doctor Mid-Nite",
  "Terry Sloane",
  "Mister Terrific",
  "Kent Nelson",
  "Doctor Fate",
  "Al Pratt",
  "Atom",
  "Johnny Thunder",
  "Thunderbolt",
  "Jakeem Thunder",
  "Sylvester Pemberton",
  "Star-Spangled Kid",
  "Pat Dugan",
  "S.T.R.I.P.E.",
  "Rex Tyler",
  "Hourman",
  "Rick Tyler",
  "Beth Chapel",
  "Doctor Mid-Nite",
  "Yolanda Montez",
  "Wildcat",
  "Albert Rothstein",
  "Nuklon",
  "Jennie-Lynn Hayden",
  "Jade",
  "Todd Rice",
  "Obsidian",
  "Courtney Whitmore",
  "Stargirl",
  "Starman",
  "Ted Knight",
  "Jack Knight",
  "David Knight",
  "Mikaal Tomas",
  "Gavyn",
  "Will Payton",
  "Thom Kallor",
  "Danny Blaine",
  "Cosmic Rod",
  "Gravity Rod",
  "Stellar Energy",
  "Black Canary",
  "Dinah Drake",
  "Dinah Laurel Lance",
  "Canary Cry",
  "Green Arrow",
  "Oliver Queen",
  "Connor Hawke",
  "Roy Harper",
  "Arsenal",
  "Speedy",
  "Mia Dearden",
  "Emiko Queen",
  "Trick Arrows",
  "Boxing Glove Arrow",
  "Justice League",
  "Watchtower",
  "Hall of Justice",
  "Satellite",
  "Happy Harbor",
  "Secret Sanctuary",
  "Superman",
  "Batman",
  "Wonder Woman",
  "Flash",
  "Green Lantern",
  "Aquaman",
  "Martian Manhunter",
  "Hawkman",
  "Hawkgirl",
  "Atom",
  "Green Arrow",
  "Black Canary",
  "Captain Marvel",
  "Shazam",
  "Billy Batson",
  "Mary Marvel",
  "Mary Batson",
  "Captain Marvel Jr.",
  "Freddy Freeman",
  "Uncle Marvel",
  "Dudley",
  "Tall Marvel",
  "Hill Marvel",
  "Fat Marvel",
  "Lieutenant Marvels",
  "Sergeant Marvel",
  "Private Marvel",
  "Wizard",
  "Shazam",
  "Mamaragan",
  "Rock of Eternity",
  "Seven Deadly Enemies of Man",
  "Pride",
  "Envy",
  "Greed",
  "Wrath",
  "Sloth",
  "Gluttony",
  "Lust",
  "Black Adam",
  "Teth-Adam",
  "Theo Adam",
  "Amon",
  "Isis",
  "Adrianna Tomaz",
  "Osiris",
  "Amon Tomaz",
  "Sobek",
  "Kahndaq",
  "Shiruta",
  "Intergang",
  "Whisper A'Daire",
  "Bruno Mannheim",
  "Crime Bible",
  "Question",
  "Cain",
  "Libra",
  "Human Flame",
  "Effigy",
  "Ocean Master",
  "Orm Marius",
  "Atlan",
  "Atlanna",
  "Tom Curry",
  "Mera",
  "Xebel",
  "Siren",
  "Hila",
  "Tula",
  "Garth",
  "Tempest",
  "Kaldur'ahm",
  "Jackson Hyde",
  "Dolphin",
  "Lagoon Boy",
  "Lori Lemaris",
  "Nuidis Vulko",
  "Murc",
  "Swatt",
  "Topo",
  "Salako",
  "Atlantean",
  "Trident of Neptune",
  "Waterbearer Hand",
  "Lady of the Lake",
  "Clear",
  "Aquaman's Harpoon",
  "Hook",
  "Martian Manhunter",
  "J'onn J'onzz",
  "M'comm M'orzz",
  "Ma'alefa'ak",
  "Cay'an",
  "White Martians",
  "Green Martians",
  "Saturnians",
  "Fire Manipulation",
  "Shape-shifting",
  "Phasing",
  "Telepathy",
  "Invisibility",
  "Super Strength",
  "Flight",
  "Heat Vision",
  "Martian Vision",
  "Ma'aleca'andra",
  "Mars",
  "H'ronmeer",
  "L'zoril",
  "M'gann M'orzz",
  "Miss Martian",
  "Hello Megan",
  "Conner Kent",
  "Superboy",
  "Match",
  "Kryptonian DNA",
  "Lex Luthor DNA",
  "Tactile Telekinesis",
  "Jon Lane Kent",
  "New 52",
  "Rebirth",
  "Young Justice",
  "Tim Drake",
  "Robin",
  "Red Robin",
  "Drake",
  "Dick Grayson",
  "Nightwing",
  "Jason Todd",
  "Red Hood",
  "Damian Wayne",
  "Robin",
  "Son of Batman",
  "Stephanie Brown",
  "Spoiler",
  "Batgirl",
  "Cassandra Cain",
  "Orphan",
  "Black Bat",
  "Batwoman",
  "Kate Kane",
  "Jacob Kane",
  "Beth Kane",
  "Alice",
  "Colony",
  "Many Arms of Death",
  "Coryana",
  "Safiyah Sohail",
  "Tahani",
  "Red Alice",
  "Religion of Crime",
  "Birds of Prey",
  "Oracle",
  "Black Canary",
  "Huntress",
  "Lady Blackhawk",
  "Zinda Blake",
  "Misfit",
  "Charlie Gage-Radcliffe",
  "Hawk and Dove",
  "Starling",
  "Ev Crawford",
  "Katana",
  "Poison Ivy",
  "Batgirl",
  "Renee Montoya",
  "Question",
  "Manhunter",
  "Kate Spencer",
  "Gotham City Sirens",
  "Catwoman",
  "Harley Quinn",
  "Poison Ivy",
  "Secret Six",
  "Deadshot",
  "Catman",
  "Scandal Savage",
  "Ragdoll",
  "Bane",
  "Jeannette",
  "King Shark",
  "Black Alice",
  "Lori Zechlin",
  "Shadowpact",
  "Nightmaster",
  "Ragdoll",
  "Blue Devil",
  "Enchantress",
  "Detective Chimp",
  "Bobo",
  "Warlord",
  "Travis Morgan",
  "Nightshade",
  "Zatanna",
  "Deadman",
  "Phantom Stranger",
  "Swamp Thing",
  "Justice League Dark",
  "John Constantine",
  "Zatanna",
  "Deadman",
  "Swamp Thing",
  "Madame Xanadu",
  "Shade the Changing Man",
  "Mindwarp",
  "Black Orchid",
  "Andrew Bennett",
  "I Vampire",
  "Cain",
  "Mary Seward",
  "Tig",
  "Professor",
  "Deacon Blackfire",
  "Etrigan",
  "Doctor Fate",
  "Animal Man",
  "Frankenstein",
  "Amethyst",
  "Princess of Gemworld",
  "Lord of Order",
  "House of Mystery",
  "House of Secrets",
  "Books of Magic",
  "Tim Hunter",
  "Rose Psychic",
  "Doctor Occult",
  "Mister E",
  "Phantom Stranger",
  "Pandora",
  "Trinity of Sin",
  "Question",
  "Judas",
  "Pandora's Box",
  "Seven Deadly Sins",
  "Council of Eternity",
  "Rock of Eternity",
  "Shazam",
  "Wizard",
  "Black Adam",
  "Isis",
  "Osiris",
  "Sobek",
  "Marvel Family",
  "Captain Marvel",
  "Mary Marvel",
  "Captain Marvel Jr.",
  "Uncle Dudley",
  "Lieutenant Marvels",
  "Tawky Tawny",
  "Mr. Mind",
  "Doctor Sivana",
  "Thaddeus Sivana",
  "Georgia Sivana",
  "Magnificus Sivana",
  "Beautia Sivana",
  "Mister Atom",
  "King Kull",
  "IBAC",
  "Sabbac",
  "Aunt Minerva",
  "Oggar",
  "Chain Lightning",
  "Seven Deadly Enemies",
  "Monster Society of Evil",
  "Crocodile-Men",
  "Herbie",
  "Jeep",
  "Nippy",
  "Steamboat",
  "Talky Tawny",
  "Sterling Morris",
  "Cissie Sommerly",
  "Billy's Parents",
  "Fawcett City",
  "WHIZ Radio",
  "Shazam!",
  "Wisdom of Solomon",
  "Strength of Hercules",
  "Stamina of Atlas",
  "Power of Zeus",
  "Courage of Achilles",
  "Speed of Mercury",
  "Lightning",
  "Magic",
  "Transformation",
  "Billy Batson",
  "Fawcett Comics",
  "National Comics",
  "DC Comics",
  "Crisis on Infinite Earths",
  "Earth-S",
  "Earth-5",
  "Multiverse",
  "New Earth",
  "Prime Earth",
  "Rebirth",
  "Infinite Frontier",
  "Dark Crisis",
  "Knight Terrors",
  "Beast World",
  "Absolute Power",
  "DC All In",
  "Superman",
  "Clark Kent",
  "Kal-El",
  "Jonathan Kent",
  "Martha Kent",
  "Lara Lor-Van",
  "Jor-El",
  "Krypton",
  "Kandor",
  "Argo City",
  "Fortress of Solitude",
  "Smallville",
  "Metropolis",
  "Daily Planet",
  "Lois Lane",
  "Jimmy Olsen",
  "Perry White",
  "Cat Grant",
  "Ron Troupe",
  "Steve Lombard",
  "Lana Lang",
  "Pete Ross",
  "Chief Parker",
  "Inspector Henderson",
  "Professor Potter",
  "Krypto",
  "Superboy",
  "Conner Kent",
  "Jon Kent",
  "Steel",
  "John Henry Irons",
  "Natasha Irons",
  "Superwoman",
  "Lana Lang",
  "Lois Lane",
  "Matrix",
  "Linda Danvers",
  "Power Girl",
  "Kara Zor-L",
  "Tanya Spears",
  "Kara Zor-El",
  "Supergirl",
  "Streaky the Supercat",
  "Comet the Superhorse",
  "Beppo the Supermonkey",
  "Legion of Super-Pets",
  "Lex Luthor",
  "LexCorp",
  "Mercy Graves",
  "Hope Taya",
  "Otis",
  "Miss Teschmacher",
  "Brainiac",
  "Vril Dox",
  "Indigo",
  "Pulsar Stargrave",
  "Bottled City",
  "Kandor",
  "Milton Fine",
  "Brainiac 5",
  "Querl Dox",
  "Supergirl",
  "Legion of Super-Heroes",
  "General Zod",
  "Ursa",
  "Non",
  "Lor-Zod",
  "Chris Kent",
  "Nightwing",
  "Flamebird",
  "Thara Ak-Var",
  "Phantom Zone",
  "Kryptonite",
  "Red Kryptonite",
  "Gold Kryptonite",
  "Blue Kryptonite",
  "White Kryptonite",
  "Black Kryptonite",
  "Silver Kryptonite",
  "Green Kryptonite",
  "Jewel Kryptonite",
  "X-Kryptonite",
  "Pink Kryptonite",
  "Bizarro",
  "Bizarro World",
  "Htrae",
  "Bizarro Lois",
  "Bizarro Jr.",
  "Bizarro Supergirl",
  "Metallo",
  "John Corben",
  "Kryptonite Heart",
  "Parasite",
  "Rudy Jones",
  "Joshua Michael Allen",
  "Alexandra Allston",
  "Toyman",
  "Winslow Schott",
  "Hiro Okamura",
  "Jack Nimball",
  "Livewire",
  "Leslie Willis",
  "Silver Banshee",
  "Siobhan Smythe",
  "Siobhan McDougal",
  "Volcana",
  "Claire Selton",
  "Atomic Skull",
  "Joseph Martin",
  "Albert Michaels",
  "Prankster",
  "Oswald Loomis",
  "Kryptonite Man",
  "K. Russell Abernathy",
  "Ultraman",
  "Earth-3",
  "Crime Syndicate",
  "Superwoman",
  "Lois Lane",
  "Owlman",
  "Thomas Wayne Jr.",
  "Johnny Quick",
  "Jonathan Allen",
  "Atomica",
  "Rhonda Pineda",
  "Deathstorm",
  "Professor Martin Stein",
  "Grid",
  "Cyborg",
  "Sea King",
  "Aquaman",
  "Mazahs",
  "Lex Luthor",
  "Alexander Luthor",
  "Forever Evil",
  "Darkseid",
  "New Gods",
  "Apokolips",
  "Granny Goodness",
  "Female Furies",
  "Kalibak",
  "Steppenwolf",
  "Desaad",
  "Parademons",
  "Boom Tube",
  "Mother Box",
  "Anti-Life Equation",
  "Omega Beams",
  "Justice League",
  "Trinity War",
  "Pandora",
  "Phantom Stranger",
  "Question",
  "Trinity of Sin",
  "Crime Syndicate",
  "Outsider",
  "Alfred Pennyworth",
  "Earth-3",
  "Ultraman",
  "Superwoman",
  "Owlman",
  "Power Ring",
  "Johnny Quick",
  "Atomica",
  "Deathstorm",
  "Sea King",
  "Grid",
  "Mazahs",
  "Alexander Luthor",
  "Forever Evil",
  "Lex Luthor",
  "Justice League",
  "Batman",
  "Superman",
  "Wonder Woman",
  "Flash",
  "Green Lantern",
  "Aquaman",
  "Cyborg",
  "Shazam",
  "Lex Luthor",
  "Captain Cold",
  "Black Manta",
  "Sinestro",
  "Deathstroke",
  "Black Adam",
  "Gorilla Grodd",
  "Cheetah",
  "Joker",
  "Harley Quinn",
  "Poison Ivy",
  "Scarecrow",
  "Riddler",
  "Penguin",
  "Catwoman",
  "Two-Face",
  "Bane",
  "Deadshot",
  "Killer Croc",
  "Mr. Freeze",
  "Clayface",
  "Mad Hatter",
  "Hugo Strange",
  "Ra's al Ghul",
  "Talia al Ghul",
  "League of Shadows",
  "Court of Owls",
  "Talon",
  "Lincoln March",
  "Thomas Wayne",
  "Flashpoint",
  "Batman",
  "Thomas Wayne",
  "Martha Wayne",
  "Joker",
  "Joe Chill",
  "Reverse Flash",
  "Eobard Thawne",
  "Professor Zoom",
  "Hunter Zolomon",
  "Zoom",
  "Daniel West",
  "Reverse Flash",
  "Godspeed",
  "August Heart",
  "Inertia",
  "Thaddeus Thawne",
  "Bart Allen",
  "Impulse",
  "Kid Flash",
  "Flash Family",
  "Jay Garrick",
  "Barry Allen",
  "Wally West",
  "Wallace West",
  "Avery Ho",
  "Jess Chambers",
  "Max Mercury",
  "Johnny Quick",
  "Savitar",
  "Lady Flash",
  "Christina Alexandrova",
  "Danica Williams",
  "Irey West",
  "Jai West",
  "Speed Force",
  "Negative Speed Force",
  "Still Force",
  "Strength Force",
  "Sage Force",
  "Forever Force",
  "Flashpoint",
  "Flash War",
  "Heroes in Crisis",
  "Death Metal",
  "Dark Nights",
  "Batman Who Laughs",
  "Robin King",
  "Dark Robin",
  "Grim Knight",
  "Bane",
  "Devastator",
  "Doomsday",
  "Murder Machine",
  "Cyborg",
  "Red Death",
  "Barry Allen",
  "Dawnbreaker",
  "Green Lantern",
  "Drowned",
  "Aquaman",
  "Merciless",
  "Wonder Woman",
  "Barbatos",
  "Dark Multiverse",
  "Nth Metal",
  "Element X",
  "Joker Dragon",
  "Castle Bat",
  "Last Knight on Earth",
  "Omega",
  "Batman",
  "Joker",
  "Arkham",
  "Gotham",
  "Wayne Manor",
  "Batcave",
  "Gotham City",
  "Metropolis",
  "Central City",
  "Keystone City",
  "Coast City",
  "Star City",
  "National City",
  "Bludhaven",
  "Hub City",
  "Ivy Town",
  "Midway City",
  "Fawcett City",
  "Happy Harbor",
  "Gateway City",
  "Themyscira",
  "Kahndaq",
  "Bialya",
  "Markovia",
  "Santa Prisca",
  "Gorilla City",
  "Nanda Parbat",
  "Atlantis",
  "Xebel",
  "Tritonis",
  "Posidonia",
  "Hy-Brasil",
  "Skartaris",
  "Gemworld",
  "Nilaa",
  "Zerox",
  "Myrra",
  "Doom Patrol",
  "Danny the Street",
  "Painting That Ate Paris",
  "Beard Hunter",
  "Flex Mentallo",
  "Crazy Jane",
  "Robotman",
  "Negative Man",
  "Elasti-Woman",
  "Mento",
  "Celsius",
  "Tempest",
  "Dorothy Spinner",
  "Chief",
  "Caulder",
  "Niles Caulder",
  "Eric Morden",
  "Mr. Nobody",
  "Brotherhood of Dada",
  "Quiz",
  "Frenzy",
  "Sleepwalk",
  "Fog",
  "Love Glove",
  "Toy",
  "Darling Come Home",
  "Agent !",
  "Red Jack",
  "Scissormen",
  "Orqwith",
  "Nürnheim",
  "Pythagoras-5",
  "Decreator",
  "Cult of the Unwritten Book",
  "Archons of Nürnheim",
  "Danny the World",
  "Danny the Brick",
  "Danny the Ambulance",
  "Danny the Island",
  "Danny the Bungalow",
  "Flex Mentallo",
  "Man of Muscle Mystery",
  "Hero of the Beach",
  "Doom Patrol",
  "My Greatest Adventure",
  "Arnold Drake",
  "Bruno Premiani",
  "Grant Morrison",
  "Rachel Pollack",
  "John Arcudi",
  "Gerard Way",
  "Young Animal",
  "Milk Wars",
  "Justice League",
  "Doom Patrol",
];

export function getMarvelName(userName) {
  if (!userName || userName.toLowerCase() === "guest") {
    const index = Math.floor(Math.random() * marvelCharacters.length);
    return marvelCharacters[index];
  }
  return userName;
}